### ISSUE TITLE
Crashing on mouse over item

### ISSUE THREAD

**Issue by Tsunayoshi** [fmauNeko/MarketBoardPlugin#12]
after opening /pmb and then mouse over an item. the progress bar fills and then i get this message.
edit: it also happens if i browse for an item and then click it.

![image](https://user-images.githubusercontent.com/5128201/115545752-74a15b00-a2a4-11eb-9a16-6d6c6b6c319b.png)

Version v0.3.0.9

**Comment by WulfRage** [comment]
i have been having this same issue as well tried to delete the plugin files and start fresh once or twice but no luck

**Comment by Tsunayoshi** [comment]
I tried it today again. And its working now. Only change was that i switched to 4k  UI Resolution. But thats maybe unrealted.

**Comment by Tsunayoshi** [comment]
seems its fixed for now

**Comment by WulfRage** [comment]
i gave it a try but didn't seem to help in my case :(

**Comment by Tsunayoshi** [comment]
I also removed mods from game. Since someone told me there are 4k Resolution now, i removed the HD Icon and Buff mods. they was from 5.1 anyway.

**Comment by WulfRage** [comment]
i went through and disabled every part from the HD icon mod. that ended up fixing it for me, so i guess it wasn't getting along with the icons from the mod. i will delete them completely now since the HD icons seem to be natively integrated into the game now and the mod author doesn't plan to do anymore updates in the future.

thanks a lot for the update i don't know how long it would have took me to figure out that it was a issue with the mod.
